### ISSUE TITLE
Error presented is incorrect

### ISSUE THREAD

**Issue by jbpratt** [RedHatQE/teflo#185] opened 2022-01-14 11:46 UTC
The error presented upon failure is not relevant. The playbook fails due to a fatal ansible task, not the output that is being shown by teflo

```
2022-01-14 05:37:01,292 INFO FAILED - RETRYING: [127.0.0.1]: Wait until RHOAM is installed (1 retries left).
2022-01-14 05:38:01,919 INFO fatal: [127.0.0.1]: FAILED! => changed=true
2022-01-14 05:38:01,919 INFO attempts: 30
2022-01-14 05:38:01,920 INFO failed_when_result: true
2022-01-14 05:38:01,920 INFO output:
2022-01-14 05:38:01,922 INFO state: installing
2022-01-14 05:38:01,923 INFO updated_timestamp: '2022-01-14T11:28:39.49225Z'
2022-01-14 05:38:01,923 INFO
2022-01-14 05:38:01,923 INFO PLAY RECAP *********************************************************************
2022-01-14 05:38:01,923 INFO 127.0.0.1                  : ok=17   changed=9    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
2022-01-14 05:38:01,923 INFO
2022-01-14 05:38:01,987 ERROR Orchestration failed : Playbook /home/bpratt/pit/git/mps/ms/solution/venv-test/solution/ansible/create_cluster.yml failed to run
The error is:
[WARNING]: Found variable using reserved name: hosts
/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vault.corp.redhat.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vault.corp.redhat.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

2022-01-14 05:38:02,034 ERROR Failed to run orchestration Provision osd cluster + install ms addons
2022-01-14 05:38:02,035 ERROR Orchestration failed : Failed to perform  Provision osd cluster + install ms addons
2022-01-14 05:38:02,036 ERROR A exception was raised while processing task: Provision osd cluster + install ms addons method: run
Traceback (most recent call last):
  File "/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/blaster/blast.py", line 83, in run
    value = getattr(task_obj, method)()
  File "/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/teflo/tasks/orchestrate.py", line 59, in run
    self.orchestrator.run()
  File "/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/teflo/orchestrators/action_orchestrator.py", line 68, in run
    raise TefloOrchestratorError("Orchestration failed : Failed to perform  %s" % self.plugin.action_name)
teflo.exceptions.TefloOrchestratorError: Orchestration failed : Failed to perform  Provision osd cluster + install ms addons

```

**Comment by dno-github** [comment] 2022-01-15 11:05
Jira ticket CCITCARBON-405 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-405

**Comment by shay6** [comment] 2022-02-03 17:15
Hey @jbpratt, can you please share the `teflo run` command and the SDF file that cause this error (with the fatal ansible task)?
It will help me to reproduce the problem

thanks

**Comment by jbpratt** [comment] 2022-02-04 11:00
Hi @shay6 , this is a very simple example. I think teflo presenting the error should probably just be removed. It isn't accurate and the error (in the case of ansible) is actually presented right above it.

`sdf.yml`
```
---
name: test
description: ...

provision:
  - name: driver
    groups:
      - localhost
    ip_address: 127.0.0.1
    ansible_params:
      ansible_connection: local

orchestrate:
  - name: test
    orchestrator: ansible
    hosts: driver
    ansible_playbook:
      name: site.yml
```

`site.yml`
```
❯ cat site.yml -p
---
- name: Test
  connection: local
  hosts: localhost
  tasks:
    - name: Demo fail
      uri:
        url: https://httpbin.org/test
        validate_certs: false
      retries: 5
      delay: 1
      register: status
      until: status.status == 200
      failed_when: status.status != 200
```

```
❯ teflo run -t provision -t orchestrate -s sdf.yml
--------------------------------------------------
Teflo Framework v2.2.2
Copyright (C) 2021, Red Hat, Inc.
--------------------------------------------------
2022-02-04 04:57:27,887 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2022-02-04 04:57:27,979 INFO

2022-02-04 04:57:27,979 INFO                                TEFLO RUN (START)
2022-02-04 04:57:27,980 INFO -------------------------------------------------------------------------------
2022-02-04 04:57:27,980 INFO  * Data Folder           : .teflo/24okvp4ajr
2022-02-04 04:57:27,981 INFO  * Workspace             : /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro
2022-02-04 04:57:27,981 INFO  * Log Level             : info
2022-02-04 04:57:27,981 INFO  * Tasks                 : ['provision', 'orchestrate']
2022-02-04 04:57:27,982 INFO  * Iterate Method        : by_level
2022-02-04 04:57:27,982 INFO  * Scenario              : test
2022-02-04 04:57:27,982 INFO -------------------------------------------------------------------------------

2022-02-04 04:57:27,983 INFO ..................................................
2022-02-04 04:57:27,983 INFO 'test' is running from the scenario file: sdf.yml
2022-02-04 04:57:27,983 INFO ..................................................
2022-02-04 04:57:27,984 INFO Sending out any notifications that are registered.
2022-02-04 04:57:27,984 INFO ..................................................
2022-02-04 04:57:27,985 INFO Starting tasks on pipeline: notify
2022-02-04 04:57:27,985 WARNING ... no tasks to be executed ...
2022-02-04 04:57:27,986 INFO  * Task    : provision
2022-02-04 04:57:27,986 INFO ..................................................
2022-02-04 04:57:27,987 INFO Starting tasks on pipeline: provision
2022-02-04 04:57:27,987 INFO --> Blaster v0.5.0 <--
2022-02-04 04:57:27,988 INFO Task Execution: Concurrent
2022-02-04 04:57:27,990 INFO Tasks:
2022-02-04 04:57:27,991 INFO 1. Task     : driver
                                Class    : <class 'teflo.tasks.provision.ProvisionTask'>
                                Methods  : ['run']
2022-02-04 04:57:27,991 INFO ** BLASTER BEGIN **
2022-02-04 04:57:28,000 WARNING Asset driver is static, provision will be skipped.
2022-02-04 04:57:28,003 INFO ** BLASTER COMPLETE **
2022-02-04 04:57:28,003 INFO     -> TOTAL DURATION: 0h:0m:0s
2022-02-04 04:57:28,004 INFO Populating inventory file with host(s) driver
2022-02-04 04:57:28,006 INFO ..................................................
2022-02-04 04:57:28,007 INFO  * Task    : orchestrate
2022-02-04 04:57:28,007 INFO ..................................................
2022-02-04 04:57:28,008 INFO Starting tasks on pipeline: orchestrate
2022-02-04 04:57:28,008 INFO --> Blaster v0.5.0 <--
2022-02-04 04:57:28,009 INFO Task Execution: Sequential
2022-02-04 04:57:28,009 INFO Tasks:
2022-02-04 04:57:28,010 INFO 1. Task     : test
                                Class    : <class 'teflo.tasks.orchestrate.OrchestrateTask'>
                                Methods  : ['run']
2022-02-04 04:57:28,010 INFO ** BLASTER BEGIN **
2022-02-04 04:57:28,012 INFO    running orchestration test for ['driver']
2022-02-04 04:57:28,015 INFO Executing playbook:
2022-02-04 04:57:28,015 INFO Ansible options used: {}
2022-02-04 04:57:28,015 INFO Executing playbook : /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/site.yml
2022-02-04 04:57:28,024 INFO 127.0.0.1
2022-02-04 04:57:28,315 INFO ansible-playbook [core 2.12.2]
2022-02-04 04:57:28,315 INFO config file = None
2022-02-04 04:57:28,315 INFO configured module search path = ['/var/home/bpratt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
2022-02-04 04:57:28,315 INFO ansible python module location = /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/venv/lib64/python3.10/site-packages/ansible
2022-02-04 04:57:28,315 INFO ansible collection location = /var/home/bpratt/.ansible/collections:/usr/share/ansible/collections
2022-02-04 04:57:28,315 INFO executable location = /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/venv/bin/ansible-playbook
2022-02-04 04:57:28,315 INFO python version = 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
2022-02-04 04:57:28,315 INFO jinja version = 3.0.3
2022-02-04 04:57:28,315 INFO libyaml = True
2022-02-04 04:57:28,315 INFO No config file found; using defaults
2022-02-04 04:57:28,381 INFO Skipping callback 'default', as we already have a stdout callback.
2022-02-04 04:57:28,382 INFO Skipping callback 'minimal', as we already have a stdout callback.
2022-02-04 04:57:28,382 INFO Skipping callback 'oneline', as we already have a stdout callback.
2022-02-04 04:57:28,382 INFO
2022-02-04 04:57:28,382 INFO PLAYBOOK: site.yml *************************************************************
2022-02-04 04:57:28,382 INFO 1 plays in /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/site.yml
2022-02-04 04:57:28,382 INFO
2022-02-04 04:57:28,382 INFO PLAY [Test] ********************************************************************
2022-02-04 04:57:28,388 INFO
2022-02-04 04:57:28,388 INFO TASK [Gathering Facts] *********************************************************
2022-02-04 04:57:28,388 INFO task path: /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/site.yml:2
2022-02-04 04:57:29,155 INFO ok: [127.0.0.1]
2022-02-04 04:57:29,161 INFO META: ran handlers
2022-02-04 04:57:29,167 INFO
2022-02-04 04:57:29,167 INFO TASK [Demo fail] ***************************************************************
2022-02-04 04:57:29,167 INFO task path: /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/site.yml:6
2022-02-04 04:57:29,803 INFO FAILED - RETRYING: [127.0.0.1]: Demo fail (5 retries left).
2022-02-04 04:57:31,252 INFO FAILED - RETRYING: [127.0.0.1]: Demo fail (4 retries left).
2022-02-04 04:57:32,691 INFO FAILED - RETRYING: [127.0.0.1]: Demo fail (3 retries left).
2022-02-04 04:57:34,081 INFO FAILED - RETRYING: [127.0.0.1]: Demo fail (2 retries left).
2022-02-04 04:57:35,600 INFO FAILED - RETRYING: [127.0.0.1]: Demo fail (1 retries left).
2022-02-04 04:57:37,046 INFO fatal: [127.0.0.1]: FAILED! => {"access_control_allow_credentials": "true", "access_control_allow_origin": "*", "attempts": 5, "changed": false, "connection": "close", "content_length": "233", "content_type": "text/html", "date": "Fri, 04 Feb 2022 10:57:52 GMT", "elapsed": 0, "failed_when_result": true, "msg": "Status code was 404 and not [200]: HTTP Error 404: NOT FOUND", "redirected": false, "server": "gunicorn/19.9.0", "status": 404, "url": "https://httpbin.org/test"}
2022-02-04 04:57:37,047 INFO
2022-02-04 04:57:37,047 INFO PLAY RECAP *********************************************************************
2022-02-04 04:57:37,047 INFO 127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
2022-02-04 04:57:37,047 INFO
2022-02-04 04:57:37,104 ERROR Orchestration failed : Playbook /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/site.yml failed to run
The error is:
[WARNING]: Found variable using reserved name: hosts

2022-02-04 04:57:37,153 ERROR Failed to run orchestration test
2022-02-04 04:57:37,154 ERROR Orchestration failed : Failed to perform  test
2022-02-04 04:57:37,155 ERROR A exception was raised while processing task: test method: run
Traceback (most recent call last):
  File "/var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/venv/lib64/python3.10/site-packages/blaster/blast.py", line 83, in run
    value = getattr(task_obj, method)()
  File "/var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/venv/lib64/python3.10/site-packages/teflo/tasks/orchestrate.py", line 59, in run
    self.orchestrator.run()
  File "/var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/venv/lib64/python3.10/site-packages/teflo/orchestrators/action_orchestrator.py", line 68, in run
    raise TefloOrchestratorError("Orchestration failed : Failed to perform  %s" % self.plugin.action_name)
teflo.exceptions.TefloOrchestratorError: Orchestration failed : Failed to perform  test
2022-02-04 04:57:38,159 INFO ** BLASTER COMPLETE **
2022-02-04 04:57:38,161 INFO     -> TOTAL DURATION: 0h:0m:10s
2022-02-04 04:57:38,162 ERROR One or more tasks got a status of non zero.
2022-02-04 04:57:38,163 INFO Sending out any notifications that are registered.
2022-02-04 04:57:38,164 INFO ..................................................
2022-02-04 04:57:38,164 INFO Starting tasks on pipeline: notify
2022-02-04 04:57:38,165 WARNING ... no tasks to be executed ...
2022-02-04 04:57:38,166 ERROR Scenario `test` failed during the Teflo run
2022-02-04 04:57:38,180 INFO

2022-02-04 04:57:38,180 INFO                                SCENARIO RUN (END)
2022-02-04 04:57:38,181 INFO -------------------------------------------------------------------------------
2022-02-04 04:57:38,181 INFO  * Duration                       : 0h:0m:10s
2022-02-04 04:57:38,182 INFO  * Passed Tasks                   : ['provision']
2022-02-04 04:57:38,182 INFO  * Failed Tasks                   : ['orchestrate']
2022-02-04 04:57:38,183 INFO  * Results Folder                 : .teflo/.results
2022-02-04 04:57:38,183 INFO  * Iterate Method                 : by_level
2022-02-04 04:57:38,184 INFO  * Scenario Definition            : test
2022-02-04 04:57:38,184 INFO  * Final Scenario Definition      : .teflo/.results/results.yml
2022-02-04 04:57:38,184 INFO -------------------------------------------------------------------------------
2022-02-04 04:57:38,185 INFO TEFLO RUN (RESULT=FAILED)
```

I'm specifically talking about this section:
```
2022-02-04 04:57:37,047 INFO 127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
2022-02-04 04:57:37,047 INFO
2022-02-04 04:57:37,104 ERROR Orchestration failed : Playbook /var/home/bpratt/git/mpqe/mps/ms/teflo-issue-185-repro/site.yml failed to run
The error is:
[WARNING]: Found variable using reserved name: hosts

2022-02-04 04:57:37,153 ERROR Failed to run orchestration test
```

and in the initial comment it is just full of SSL warnings which are not interesting :smile_cat: 
```
2022-01-14 05:38:01,987 ERROR Orchestration failed : Playbook /home/bpratt/pit/git/mps/ms/solution/venv-test/solution/ansible/create_cluster.yml failed to run
The error is:
[WARNING]: Found variable using reserved name: hosts
/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vault.corp.redhat.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/bpratt/pit/git/mps/ms/solution/venv-test/lib64/python3.10/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vault.corp.redhat.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

2022-01-14 05:38:02,034 ERROR Failed to run orchestration Provision osd cluster + install ms addons
```

**Comment by shay6** [comment] 2022-02-16 14:22
hey @jbpratt, sorry for the late reply.

that error is an `ansible-playbook` command error. The Teflo run the following command:
`ansible-playbook -i <path_to_inventory> <path_to_site.yml > -e hosts="\\'driver\\'" -e uuid="\\'tl7bx\\'" -e "{\\'localhost\\': True}"`

But `hosts` is a reserved variable in ansible (see here [1] ) so it's not a valid name (see here [2]).

I couldn't find a workaround to ignore this error/warning during the run.
I'll keep you updated about the progress.


[1] https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html#play
[2] https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#creating-valid-variable-names

**Comment by jbpratt** [comment] 2022-02-16 14:26
Hi @shay6 , I don't actually care about the warning, we can keep using the variable (we depend on it). My issue is that the error block should not be present since it is incorrect.

Changing `hosts` to a different variable name is a _HUGE_ change and should not be done.

**Comment by shay6** [comment] 2022-02-16 14:37
yes, @jbpratt, you are right about changing the `hosts` variable, it's a HUGE change.

but IIUC, the problem is that ansible relates to this warning as an Error, it goes to `stderr`.

**Comment by jbpratt** [comment] 2022-02-16 14:39
I agree, since it goes to stderr it will be picked up (the same as HTTPS verification warnings from python). This is why I lean towards removing the feature completely, I don't think there is a good way to present that without duplicating stuff (the ansible error is presented clearly above).

**Comment by shay6** [comment] 2022-02-28 09:28
fixed with https://github.com/RedHatQE/teflo/pull/201

**Closed** 2022-02-28 09:28 UTC
Labels: jira_ticket_exist
